"""Assembling the looped G-code.

Each loop is::

    ; >>> LOOP i / n <<<
    <header + config on the first loop, M400 on the others>
    <setup commands, up to and including "; FEATURE: Custom">
    <patched slicer start code>
    M220 S100
    <the print>
    <patched slicer end code: cool down + push off>

The last loop may end differently: that is where the head is parked, since the
job is over once it has run.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone

from .constants import LOOPRINT_SIGNATURE
from .structure import GcodeStructure

CONTACT = "Nicki.Andersen@gmail.com"
PROJECT_URL = "https://github.com/NickiAndersen/looprint"


@dataclass(frozen=True)
class LoopPlan:
    """Everything needed to emit the looped file."""

    structure: GcodeStructure
    start_code: str
    end_code: str
    loops: int
    source_name: str
    #: End code for the last loop, when it differs - that is the one that parks
    #: the head, since the job is over once it has run.
    final_end_code: str | None = None
    generated_at: datetime | None = None


def build_looped_gcode(plan: LoopPlan) -> str:
    parts: list[str] = _banner(plan.loops, plan.source_name, plan.generated_at)
    for index in range(1, plan.loops + 1):
        parts.extend(_one_loop(plan, index))
    parts.append("; >>> END OF PRINT LOOPS <<<")
    parts.append("M220 S100 ; Reset to standard speed\n")
    parts.append(f"; ===== {LOOPRINT_SIGNATURE} (End) =====")
    return "\n".join(parts)


def _banner(loops: int, source_name: str, generated_at: datetime | None) -> list[str]:
    stamp = (generated_at or datetime.now(timezone.utc)).astimezone(timezone.utc)
    return [
        f"; ===== {LOOPRINT_SIGNATURE} (Start) =====",
        f"; Source: {source_name}",
        f"; Loops: {loops}",
        f"; Generated: {_iso(stamp)}",
        "; Generated by Looprint",
        f"; Contact: {CONTACT}",
        f"; GitHub: {PROJECT_URL}",
        "\n",
    ]


def _one_loop(plan: LoopPlan, index: int) -> list[str]:
    structure = plan.structure
    parts = [f"; >>> LOOP {index} / {plan.loops} <<<"]

    if index == 1:
        if structure.header:
            parts += [structure.header, "\n"]
        if structure.config:
            parts += [structure.config, "\n"]
    else:
        parts += ["M400 ; Looprint safety: Wait for buffer clear before next loop", "\n"]

    parts += [structure.setup, "\n", plan.start_code, "\n"]
    parts += ["M220 S100 ; Set speed mode\n", structure.print_body, "\n"]
    last = index == plan.loops and plan.final_end_code is not None
    parts += [plan.final_end_code if last else plan.end_code, "\n"]
    return parts


def _iso(stamp: datetime) -> str:
    """``Date.prototype.toISOString`` - always UTC, always milliseconds."""
    return stamp.strftime("%Y-%m-%dT%H:%M:%S.") + f"{stamp.microsecond // 1000:03d}Z"
