"""Markers and signatures shared by every printer."""

from __future__ import annotations

import re

LOOPRINT_SIGNATURE = "Looprint Loop File"

#: The slicer writes its machine end G-code right after this comment, so the
#: last occurrence of it is where the original end code begins.
END_CODE_START_MARKER = ";===== date:"

HEADER_BLOCK_END = "; HEADER_BLOCK_END"
CONFIG_BLOCK_START = "; CONFIG_BLOCK_START"
CONFIG_BLOCK_END = "; CONFIG_BLOCK_END"
EXECUTABLE_BLOCK_START = "; EXECUTABLE_BLOCK_START"
FEATURE_CUSTOM = "; FEATURE: Custom"

#: Path of the plate G-code inside a 3MF container.
GCODE_IN_3MF_RE = re.compile(r"^Metadata/plate_\d+\.gcode$", re.IGNORECASE)

#: First marker of the real print; everything between ``FEATURE_CUSTOM`` and it
#: is the slicer's start code and gets replaced.
LAYER_MARKER_RE = re.compile(
    r"; CHANGE_LAYER|;LAYER_CHANGE|; layer num/total_layer_count|; layer "
    r"|;Z_HEIGHT|;LAYER_NUM|; GEOMETRY_START",
    re.IGNORECASE,
)

MAX_Z_HEIGHT_RE = re.compile(r";\s*max_z_height\s*[:=]\s*([\d.]+)", re.IGNORECASE)
MAX_Z_HEIGHT_MM = 1000
FALLBACK_MAX_Z_HEIGHT_MM = 50.0

#: Anything containing one of these has already been through Looprint.
LOOPRINT_WATERMARKS = (
    LOOPRINT_SIGNATURE,
    "Generated by Looprint",
    "Contact: Nicki.Andersen@gmail.com",
    "github.com/NickiAndersen/looprint",
)
