"""Assembling the looped G-code.

Each loop is::

    ; >>> LOOP i / n <<<
    <header + config on the first loop, M400 on the others>
    <setup commands, up to and including "; FEATURE: Custom">
    <patched slicer start code>
    M220 S<speed>
    <the print>
    <patched slicer end code: cool down + push off>
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timezone

from .constants import LOOPRINT_SIGNATURE
from .structure import GcodeStructure

_M220_RESET_RE = re.compile(r"M220\s+S100\b")

CONTACT = "Nicki.Andersen@gmail.com"
PROJECT_URL = "https://github.com/NickiAndersen/looprint"


@dataclass(frozen=True)
class LoopPlan:
    """Everything needed to emit the looped file."""

    structure: GcodeStructure
    start_code: str
    end_code: str
    loops: int
    speed_mode: int
    source_name: str
    nozzle_temperature: str | None = None
    generated_at: datetime | None = None


def build_looped_gcode(plan: LoopPlan) -> str:
    parts: list[str] = _banner(plan.loops, plan.source_name, plan.generated_at)
    for index in range(1, plan.loops + 1):
        parts.extend(_one_loop(plan, index))
    parts.append("; >>> END OF PRINT LOOPS <<<")
    parts.append("M220 S100 ; Reset to standard speed\n")
    parts.append(f"; ===== {LOOPRINT_SIGNATURE} (End) =====")
    return "\n".join(parts)


def _banner(loops: int, source_name: str, generated_at: datetime | None) -> list[str]:
    stamp = (generated_at or datetime.now(timezone.utc)).astimezone(timezone.utc)
    return [
        f"; ===== {LOOPRINT_SIGNATURE} (Start) =====",
        f"; Source: {source_name}",
        f"; Loops: {loops}",
        f"; Generated: {_iso(stamp)}",
        "; Generated by Looprint",
        f"; Contact: {CONTACT}",
        f"; GitHub: {PROJECT_URL}",
        "\n",
    ]


def _one_loop(plan: LoopPlan, index: int) -> list[str]:
    structure = plan.structure
    parts = [f"; >>> LOOP {index} / {plan.loops} <<<"]

    if index == 1:
        if structure.header:
            parts += [structure.header, "\n"]
        if structure.config:
            parts += [structure.config, "\n"]
    else:
        parts += ["M400 ; Looprint safety: Wait for buffer clear before next loop", "\n"]

    parts += [structure.setup, "\n", plan.start_code, "\n"]
    parts += _print_section(plan)
    parts += [plan.end_code, "\n"]
    return parts


def _print_section(plan: LoopPlan) -> list[str]:
    body = plan.structure.print_body
    if plan.speed_mode != 100:
        # The slicer sprinkles M220 S100 through the print; leaving them would
        # undo the requested speed part-way through a loop.
        body = _M220_RESET_RE.sub(f"M220 S{plan.speed_mode}", body)
    return [f"M220 S{plan.speed_mode} ; Set speed mode\n", body, "\n"]


def _iso(stamp: datetime) -> str:
    """``Date.prototype.toISOString`` - always UTC, always milliseconds."""
    return stamp.strftime("%Y-%m-%dT%H:%M:%S.") + f"{stamp.microsecond // 1000:03d}Z"
