"""Assembling the looped G-code.

Common to every printer.  Each loop is::

    ; >>> LOOP i / n <<<
    <header + config on the first loop, M400 on the others>
    <setup commands, up to and including "; FEATURE: Custom">
    <printer start code>
    M220 S<speed>
    <the print>
    <printer end code: cool down + push off>
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timezone

from .constants import LOOPRINT_SIGNATURE
from .structure import GcodeStructure

_LAYER_START_RE = re.compile(r"^;LAYER_CHANGE|^; layer|^;LAYER", re.IGNORECASE)
_M220_RESET_RE = re.compile(r"M220\s+S100\b")

CONTACT = "Nicki.Andersen@gmail.com"
PROJECT_URL = "https://github.com/NickiAndersen/looprint"


@dataclass(frozen=True)
class LoopPlan:
    """Everything needed to emit the looped file."""

    structure: GcodeStructure
    start_code: str
    end_code: str
    loops: int
    speed_mode: int
    source_name: str
    nozzle_temperature: str | None = None
    generated_at: datetime | None = None


def build_looped_gcode(plan: LoopPlan) -> str:
    parts: list[str] = list(_banner(plan))
    for index in range(1, plan.loops + 1):
        parts.extend(_one_loop(plan, index))
    parts.append("; >>> END OF PRINT LOOPS <<<")
    parts.append("M220 S100 ; Reset to standard speed\n")
    parts.append(f"; ===== {LOOPRINT_SIGNATURE} (End) =====")
    return "\n".join(parts)


def _banner(plan: LoopPlan) -> list[str]:
    stamp = (plan.generated_at or datetime.now(timezone.utc)).astimezone(timezone.utc)
    return [
        f"; ===== {LOOPRINT_SIGNATURE} (Start) =====",
        f"; Source: {plan.source_name}",
        f"; Loops: {plan.loops}",
        f"; Generated: {_iso(stamp)}",
        "; Generated by Looprint",
        f"; Contact: {CONTACT}",
        f"; GitHub: {PROJECT_URL}",
        "\n",
    ]


def _one_loop(plan: LoopPlan, index: int) -> list[str]:
    structure = plan.structure
    parts = [f"; >>> LOOP {index} / {plan.loops} <<<"]

    if index == 1:
        if structure.header:
            parts += [structure.header, "\n"]
        if structure.config:
            parts += [structure.config, "\n"]
    else:
        parts += ["M400 ; Looprint safety: Wait for buffer clear before next loop", "\n"]

    if structure.recognised and structure.setup:
        parts += [structure.setup, "\n", plan.start_code, "\n"]
        if structure.print_body:
            parts += _print_section(plan)
    else:
        # Unrecognised layout: emit the file as-is, and only prepend a start code
        # if one is evidently not in there already.
        body = structure.setup
        if "machine: P1S" not in body and "FactorianDesigns" not in body:
            parts += [plan.start_code, "\n", f"M220 S{plan.speed_mode} ; Set speed mode\n"]
        parts += [body, "\n"]

    parts += [plan.end_code, "\n"]
    return parts


def _print_section(plan: LoopPlan) -> list[str]:
    parts: list[str] = []
    body = plan.structure.print_body

    if _LAYER_START_RE.match(body.strip()) and plan.nozzle_temperature:
        parts.append("; Ensure nozzle temperature is set for printing\n")
        parts.append(f"M104 S{plan.nozzle_temperature} ; Set nozzle temp for printing\n")
        parts.append("\n")

    parts.append(f"M220 S{plan.speed_mode} ; Set speed mode\n")
    if plan.speed_mode != 100:
        # The slicer sprinkles M220 S100 through the print; leaving them would
        # undo the requested speed part-way through a loop.
        body = _M220_RESET_RE.sub(f"M220 S{plan.speed_mode}", body)
    parts.append(body)
    parts.append("\n")
    return parts


def _iso(stamp: datetime) -> str:
    """``Date.prototype.toISOString`` - always UTC, always milliseconds."""
    return stamp.strftime("%Y-%m-%dT%H:%M:%S.") + f"{stamp.microsecond // 1000:03d}Z"
